/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1_0;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author matgr
 */
public class Frmfactura extends javax.swing.JFrame implements Printable {

    /**
     * Creates new form Frmfactura
     */
    String[] sep;
    String sep1;

    public Frmfactura(int cantidad, String nombre, String ruta, double precio, double total) {
        initComponents();
        //sep1= ruta;
        Date fa = new Date();
        String mesctual1 = null;
        String diaactual1 = "";
        int aniactual = fa.getYear() + 1900;
        int mesctual = fa.getMonth() + 1;
        int diaactual = fa.getDate();
        if (mesctual < 10) {
            mesctual1 = "0" + mesctual;
        } else {
            mesctual1 = "" + mesctual;
        }
        if (diaactual < 10) {
            diaactual1 = "0" + diaactual;
        } else {
            diaactual1 = "" + diaactual;
        }
        lblfecha.setText(diaactual1 + "-" + mesctual1 + "-" + aniactual);
        buscar(nombre);
        tabla(cantidad, ruta, precio, total);
    }

    private Frmfactura() {

    }

    private void tabla(int cantidad, String ruta, double precio, double total) {
        DefaultTableModel modelo = new DefaultTableModel();
        tbldescripcion.setModel(modelo);
        String[] fila = new String[4];
        float nt = (float) 0.0;
        int[] anchos = {30, 100, 50, 50};

        modelo.addColumn("Cantidad");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Precio Unitario");
        modelo.addColumn("Precio Cantidad");
        for (int i = 0; i < tbldescripcion.getColumnCount(); i++) {
            tbldescripcion.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
        }
        sep = ruta.split("-");
        fila[0] = "" + cantidad;
        fila[1] = "Viaje " + sep[1] +" - "+ sep[2];
        fila[2] = "" + precio;
        fila[3] = "" + total;

        lbltotal.setText("" + total + "0");
        modelo.addRow(fila);
    }

    private void buscar(String nombre) {
        PreparedStatement ps = null;
        ResultSet rs = null;
        Conexion conn = new Conexion();

        try {
            System.out.println(nombre);
            java.sql.Connection con = conn.getConexion();
            ps = con.prepareStatement("SELECT * FROM cliente WHERE Nombre = ?");
            ps.setString(1, nombre);

            rs = ps.executeQuery();

            if (rs.next()) {
                lblcedula1.setText(rs.getString("Cedula"));
                lblnombre.setText(rs.getString("Nombre"));
                lbltelefono.setText(rs.getString("Telefono"));
                lbldireccion.setText(rs.getString("Direccion"));
                lblnumero.setText("00" + rs.getString("Id"));

            } else {
                JOptionPane.showMessageDialog(null, "Cliente no encontrado");
            }

        } catch (Exception e) {
            System.err.println(e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlfactura = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblnumero = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbldireccion = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        lblfecha = new javax.swing.JLabel();
        lbltelefono = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblcedula1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldescripcion = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        lbltotal = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnimprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        pnlfactura.setBackground(new java.awt.Color(255, 255, 255));
        pnlfactura.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("N°");
        pnlfactura.add(jLabel5);
        jLabel5.setBounds(484, 0, 29, 39);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("             FACTURA");
        pnlfactura.add(jLabel6);
        jLabel6.setBounds(120, 0, 248, 39);

        lblnumero.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblnumero.setText("...");
        pnlfactura.add(lblnumero);
        lblnumero.setBounds(531, 0, 79, 39);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Nombre:");
        pnlfactura.add(jLabel1);
        jLabel1.setBounds(19, 57, 68, 26);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Teléfono:");
        pnlfactura.add(jLabel2);
        jLabel2.setBounds(356, 101, 68, 16);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Fecha:");
        pnlfactura.add(jLabel3);
        jLabel3.setBounds(356, 57, 68, 26);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Cédula:");
        pnlfactura.add(jLabel4);
        jLabel4.setBounds(18, 101, 68, 16);

        lbldireccion.setText("...");
        pnlfactura.add(lbldireccion);
        lbldireccion.setBounds(113, 130, 485, 16);

        lblnombre.setText("...");
        pnlfactura.add(lblnombre);
        lblnombre.setBounds(113, 62, 179, 16);

        lblfecha.setText("...");
        pnlfactura.add(lblfecha);
        lblfecha.setBounds(431, 62, 179, 16);

        lbltelefono.setText("...");
        pnlfactura.add(lbltelefono);
        lbltelefono.setBounds(431, 101, 179, 16);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("Dirección:");
        pnlfactura.add(jLabel8);
        jLabel8.setBounds(18, 130, 68, 16);

        lblcedula1.setText("...");
        pnlfactura.add(lblcedula1);
        lblcedula1.setBounds(113, 101, 179, 16);

        tbldescripcion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbldescripcion);

        pnlfactura.add(jScrollPane1);
        jScrollPane1.setBounds(0, 174, 598, 112);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("TOTAL:");
        pnlfactura.add(jLabel9);
        jLabel9.setBounds(388, 358, 68, 26);

        lbltotal.setText("...");
        pnlfactura.add(lbltotal);
        lbltotal.setBounds(483, 358, 68, 26);

        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlfactura.add(jLabel7);
        jLabel7.setBounds(468, 9, 130, 30);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnimprimir.setText("Imprimir");
        btnimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnimprimir)
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnimprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlfactura, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlfactura, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimirActionPerformed
        try {
            PrinterJob gsp = PrinterJob.getPrinterJob();
            gsp.setPrintable(this);
            boolean top = gsp.printDialog();
            if (top) {
                gsp.print();
            }
        } catch (PrinterException pex) {
            JOptionPane.showMessageDialog(null, "ERROR DE PROGRAMA", "Error\n" + pex, JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnimprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frmfactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frmfactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frmfactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frmfactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frmfactura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnimprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcedula1;
    private javax.swing.JLabel lbldireccion;
    private javax.swing.JLabel lblfecha;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblnumero;
    private javax.swing.JLabel lbltelefono;
    private javax.swing.JLabel lbltotal;
    private javax.swing.JPanel pnlfactura;
    private javax.swing.JTable tbldescripcion;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics graf, PageFormat pagfor, int index) throws PrinterException {
        if (index > 0) {
            return NO_SUCH_PAGE;
        }
        Graphics2D hub = (Graphics2D) graf;
        hub.translate(pagfor.getImageableX() + 30, pagfor.getImageableY() + 30);
        hub.scale(1.0, 1.0);
        pnlfactura.printAll(graf);
        return PAGE_EXISTS;
    }
}
