/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1_0;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author matgr
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);

        // this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        panelIngresos = new javax.swing.JPanel();
        btnBoletos = new javax.swing.JButton();
        btnConductores = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnRutas = new javax.swing.JButton();
        btnBus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelIngresos.setBackground(new java.awt.Color(255, 255, 255));
        panelIngresos.setLayout(new java.awt.GridBagLayout());
        jPanel2.add(panelIngresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 770, -1));

        btnBoletos.setBackground(new java.awt.Color(255, 255, 255));
        btnBoletos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBoletos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-boleto-50.png"))); // NOI18N
        btnBoletos.setText("Venta Boletos");
        btnBoletos.setBorder(null);
        btnBoletos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBoletos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBoletosMousePressed(evt);
            }
        });
        btnBoletos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoletosActionPerformed(evt);
            }
        });
        jPanel2.add(btnBoletos, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 160, 40));

        btnConductores.setBackground(new java.awt.Color(255, 255, 255));
        btnConductores.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnConductores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-conductor-50.png"))); // NOI18N
        btnConductores.setText("Registro Conductores");
        btnConductores.setBorder(null);
        btnConductores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConductores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnConductoresMousePressed(evt);
            }
        });
        btnConductores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConductoresActionPerformed(evt);
            }
        });
        jPanel2.add(btnConductores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 40));

        btnClientes.setBackground(new java.awt.Color(255, 255, 255));
        btnClientes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-gestión-de-clientes-50.png"))); // NOI18N
        btnClientes.setText("Registro Clientes");
        btnClientes.setBorder(null);
        btnClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnClientesMousePressed(evt);
            }
        });
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        jPanel2.add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 170, 40));

        btnRutas.setBackground(new java.awt.Color(255, 255, 255));
        btnRutas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRutas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-mapa-del-tesoro-50.png"))); // NOI18N
        btnRutas.setText("Registro Rutas");
        btnRutas.setBorder(null);
        btnRutas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRutas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRutasMousePressed(evt);
            }
        });
        btnRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRutasActionPerformed(evt);
            }
        });
        jPanel2.add(btnRutas, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 160, 40));

        btnBus.setBackground(new java.awt.Color(255, 255, 255));
        btnBus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-ancho-de-bus-50.png"))); // NOI18N
        btnBus.setText("Registro Buses");
        btnBus.setBorder(null);
        btnBus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBusMousePressed(evt);
            }
        });
        btnBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusActionPerformed(evt);
            }
        });
        jPanel2.add(btnBus, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 160, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/551984.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-500, 0, 1360, 750));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBoletosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBoletosMousePressed
        this.btnBoletos.setSelected(true);
        this.btnConductores.setSelected(false);
        this.btnClientes.setSelected(false);
        this.btnBus.setSelected(false);
        this.btnRutas.setSelected(false);
    }//GEN-LAST:event_btnBoletosMousePressed

    private void btnBoletosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoletosActionPerformed
        if (this.btnBoletos.isSelected()) {
            new proyecto1_0.CambiaPanel(panelIngresos, new PanelVentas());
        }
    }//GEN-LAST:event_btnBoletosActionPerformed

    private void btnConductoresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConductoresMousePressed
        this.btnBoletos.setSelected(false);
        this.btnConductores.setSelected(true);
        this.btnClientes.setSelected(false);
        this.btnBus.setSelected(false);
        this.btnRutas.setSelected(false);
    }//GEN-LAST:event_btnConductoresMousePressed

    private void btnConductoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConductoresActionPerformed
        if (this.btnConductores.isSelected()) {
            new proyecto1_0.CambiaPanel(panelIngresos, new PanelConductores());
        }
    }//GEN-LAST:event_btnConductoresActionPerformed

    private void btnClientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMousePressed
        this.btnBoletos.setSelected(false);
        this.btnConductores.setSelected(false);
        this.btnClientes.setSelected(true);
        this.btnBus.setSelected(false);
        this.btnRutas.setSelected(false);

    }//GEN-LAST:event_btnClientesMousePressed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        if (this.btnClientes.isSelected()) {
            new proyecto1_0.CambiaPanel(panelIngresos, new PanelClientes());
        }
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnRutasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRutasMousePressed
        this.btnBoletos.setSelected(false);
        this.btnConductores.setSelected(false);
        this.btnClientes.setSelected(false);
        this.btnBus.setSelected(false);
        this.btnRutas.setSelected(true);
    }//GEN-LAST:event_btnRutasMousePressed

    private void btnRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRutasActionPerformed
        if (this.btnRutas.isSelected()) {
            new proyecto1_0.CambiaPanel(panelIngresos, new PanelRutas());
        }
    }//GEN-LAST:event_btnRutasActionPerformed

    private void btnBusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBusMousePressed
        this.btnBoletos.setSelected(false);
        this.btnConductores.setSelected(false);
        this.btnClientes.setSelected(false);
        this.btnBus.setSelected(true);
        this.btnRutas.setSelected(false);
    }//GEN-LAST:event_btnBusMousePressed

    private void btnBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusActionPerformed
        if (this.btnBus.isSelected()) {
            new proyecto1_0.CambiaPanel(panelIngresos, new PanelBuses());
        }
    }//GEN-LAST:event_btnBusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBoletos;
    private javax.swing.JButton btnBus;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnConductores;
    private javax.swing.JButton btnRutas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelIngresos;
    // End of variables declaration//GEN-END:variables

}
