/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1_0;

import Atxy2k.CustomTextField.RestrictedTextField;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author matgr
 */
public class PanelConductores extends javax.swing.JPanel {

    /**
     * Creates new form PanelConductores
     */
    public PanelConductores() {
        initComponents();
        tabla();
      txtId.setVisible(false);
       RestrictedTextField r = new RestrictedTextField(txtcedula2);
        r.setLimit(10);
      RestrictedTextField r1 = new RestrictedTextField(txtClave2);
        r1.setLimit(10);
      RestrictedTextField r2 = new RestrictedTextField(txttelefono3);
        r2.setLimit(10);
      RestrictedTextField r3 = new RestrictedTextField(txtlicencia);
        r3.setLimit(10);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        JPNregistrar2 = new javax.swing.JPanel();
        lblCedula2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtnombre2 = new javax.swing.JTextField();
        txtcedula2 = new javax.swing.JTextField();
        JBTguardar2 = new javax.swing.JButton();
        lblFechaNac7 = new javax.swing.JLabel();
        txtlicencia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtClave2 = new javax.swing.JTextField();
        btnBuscar2 = new javax.swing.JButton();
        Modificar2 = new javax.swing.JButton();
        eliminar2 = new javax.swing.JButton();
        lblFechaNac8 = new javax.swing.JLabel();
        txttelefono3 = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtconductores = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab1", jTabbedPane4);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("             CONDUCTORES");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        JPNregistrar2.setBackground(new java.awt.Color(255, 255, 255));

        lblCedula2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lblCedula2.setText("#Cédula:");

        jLabel6.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel6.setText("Nombre:");

        txtnombre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombre2ActionPerformed(evt);
            }
        });
        txtnombre2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombre2KeyTyped(evt);
            }
        });

        txtcedula2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcedula2ActionPerformed(evt);
            }
        });
        txtcedula2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcedula2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcedula2KeyTyped(evt);
            }
        });

        JBTguardar2.setText("Registrar");
        JBTguardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTguardar2ActionPerformed(evt);
            }
        });

        lblFechaNac7.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lblFechaNac7.setText("Licencia:");

        txtlicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlicenciaActionPerformed(evt);
            }
        });
        txtlicencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtlicenciaKeyTyped(evt);
            }
        });

        jLabel7.setText("Ingrese el número de cédula del conductor:");

        txtClave2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClave2KeyTyped(evt);
            }
        });

        btnBuscar2.setText("Buscar");
        btnBuscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar2ActionPerformed(evt);
            }
        });

        Modificar2.setText("Modificar");
        Modificar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modificar2ActionPerformed(evt);
            }
        });

        eliminar2.setText("Eliminar");
        eliminar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar2ActionPerformed(evt);
            }
        });

        lblFechaNac8.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lblFechaNac8.setText("Teléfono:");

        txttelefono3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelefono3ActionPerformed(evt);
            }
        });
        txttelefono3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelefono3KeyTyped(evt);
            }
        });

        txtId.setBackground(java.awt.SystemColor.control);
        txtId.setForeground(new java.awt.Color(255, 255, 255));
        txtId.setCaretColor(new java.awt.Color(255, 255, 255));
        txtId.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtId.setEnabled(false);

        javax.swing.GroupLayout JPNregistrar2Layout = new javax.swing.GroupLayout(JPNregistrar2);
        JPNregistrar2.setLayout(JPNregistrar2Layout);
        JPNregistrar2Layout.setHorizontalGroup(
            JPNregistrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPNregistrar2Layout.createSequentialGroup()
                .addGroup(JPNregistrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPNregistrar2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(JPNregistrar2Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(JPNregistrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JBTguardar2)
                            .addGroup(JPNregistrar2Layout.createSequentialGroup()
                                .addGroup(JPNregistrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFechaNac8)
                                    .addComponent(lblCedula2)
                                    .addComponent(lblFechaNac7)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)))
                        .addGroup(JPNregistrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPNregistrar2Layout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addGroup(JPNregistrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcedula2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtClave2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txttelefono3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtlicencia, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(JPNregistrar2Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(Modificar2)
                                .addGap(47, 47, 47)
                                .addComponent(eliminar2)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(JPNregistrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar2)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
        JPNregistrar2Layout.setVerticalGroup(
            JPNregistrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNregistrar2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(JPNregistrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar2)
                    .addComponent(txtClave2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(JPNregistrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(JPNregistrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPNregistrar2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(JPNregistrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcedula2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblCedula2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPNregistrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaNac8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttelefono3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPNregistrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaNac7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtlicencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(JPNregistrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBTguardar2)
                    .addComponent(Modificar2)
                    .addComponent(eliminar2))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JPNregistrar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JPNregistrar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane5.addTab("Registro Conductores", jPanel2);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jtconductores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Cedula", "Nombre", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtconductores);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jTabbedPane5.addTab("Tabla conductores", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombre2ActionPerformed

    private void txtnombre2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombre2KeyTyped

        if (validaIngresos(evt, 1)) {
            JOptionPane.showMessageDialog(null, "Este campo no acepta numeros");
        }
    }//GEN-LAST:event_txtnombre2KeyTyped

    private void txtcedula2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcedula2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcedula2ActionPerformed

    private void txtcedula2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcedula2KeyReleased
        PreparedStatement ps = null;
        ResultSet rs = null;
        Conexion conn = new Conexion();

        try {

            java.sql.Connection con = conn.getConexion();
            ps = con.prepareStatement("SELECT * FROM conductor WHERE Cedula = ?");
            ps.setString(1, txtcedula2.getText());

            rs = ps.executeQuery();

            if (rs.next()) {

                txtId.setText(txtcedula2.getText());

            } else {
                //JOptionPane.showMessageDialog(null, "Usuario no encontrado");
            }

        } catch (Exception e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_txtcedula2KeyReleased

    private void txtcedula2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcedula2KeyTyped

        if (validaIngresos(evt, 2)) {
            JOptionPane.showMessageDialog(null, "Este campo no acepta letras");
        }
    }//GEN-LAST:event_txtcedula2KeyTyped

    private void JBTguardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTguardar2ActionPerformed
        PreparedStatement ps = null;
        int num, contador = 2;
        
        String comp = txtId.getText();
        System.out.println(comp);
        

        //int Fila = tablausuarios.getSelectedRow();
        String comp1 = "";
        System.out.println(comp);
        if ("".equals(comp)) {
            comp = ".";
        }
        if ((comp1.equals(txtcedula2.getText())) || (comp1.equals(txtnombre2.getText())) || (comp1.equals(txttelefono3.getText())) || (comp1.equals(txtlicencia.getText())) ) {
            JOptionPane.showMessageDialog(null, "Porfavor llene todos los campos");
        } else {
            if ((comp.equals(txtcedula2.getText()))) {
                JOptionPane.showMessageDialog(null, "El conductor ya se encuentra registrado");
            } else {
                num = Integer.parseInt(txtcedula2.getText());
                while (num / 10 > 0) {
                    num = num / 10;
                    contador++;
                }
               System.out.println(""+contador);
                if ((contador == 10)) {
                   try {
                        Conexion objCon = new Conexion();
                        Connection conn = objCon.getConexion();
                        ps = conn.prepareStatement("INSERT INTO conductor (Cedula, Nombre, Telefono, Licencia) VALUES (?,?,?,?)");
                        ps.setString(1, txtcedula2.getText());
                        ps.setString(2, txtnombre2.getText());

                        ps.setString(3, txttelefono3.getText());
                        ps.setString(4, txtlicencia.getText());
                        

                        ps.execute();
                        JOptionPane.showMessageDialog(null, "Conductor Registrado");

                        limpiar();
                       

                    } catch (SQLException ex) {
                        
                        System.out.println(ex);
                        JOptionPane.showMessageDialog(null, "Error al registrar Conductor");
                    } 
                }
                    
                
                   
                    if (contador != 10) {
                        JOptionPane.showMessageDialog(null, "La cédula debe tener 10 dígitos");
                    }
                     tabla();

            }

            

        }
    }//GEN-LAST:event_JBTguardar2ActionPerformed

    private void txtlicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlicenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlicenciaActionPerformed

    private void txtlicenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlicenciaKeyTyped
        if (validaIngresos(evt, 2)) {
            JOptionPane.showMessageDialog(null, "Este campo no acepta letras");
        }
    }//GEN-LAST:event_txtlicenciaKeyTyped

    private void txtClave2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClave2KeyTyped

        if (validaIngresos(evt, 2)) {
            JOptionPane.showMessageDialog(null, "Este campo no acepta letras");
        }
    }//GEN-LAST:event_txtClave2KeyTyped

    private void btnBuscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar2ActionPerformed
        RestrictedTextField r = new RestrictedTextField(txtcedula2);
           //RestrictedTextField p=new RestrictedTextField(txtClave2);

        // p.setLimit(10);
        //p.setOnlyNums(true);
        PreparedStatement ps = null;
        ResultSet rs = null;
        Conexion conn = new Conexion();

        try {

            java.sql.Connection con = conn.getConexion();
            ps = con.prepareStatement("SELECT * FROM conductor WHERE Cedula = ?");
            ps.setString(1, txtClave2.getText());

            rs = ps.executeQuery();

            if (rs.next()) {
                txtcedula2.setText(rs.getString("Cedula"));
                txtnombre2.setText(rs.getString("Nombre"));
                txttelefono3.setText(rs.getString("Telefono"));
                
                txtlicencia.setText(rs.getString("Licencia"));
                txtId.setText(txtClave2.getText());

            } else {
                JOptionPane.showMessageDialog(null, "Conductor no encontrado");
            }

        } catch (Exception e) {
            System.err.println(e);
        }

        txtClave2.setText("");
    }//GEN-LAST:event_btnBuscar2ActionPerformed

    private void Modificar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Modificar2ActionPerformed
        // Conexion conn = new Conexion();
        PreparedStatement ps = null;
        //int Fila = tablausuarios.getSelectedRow();
        if (("".equals(txtcedula2.getText())) || ("".equals(txtnombre2.getText())) || ("".equals(txttelefono3.getText())) || ("".equals(txtlicencia.getText()))) {
            JOptionPane.showMessageDialog(null, "Todos los campos deben estar llenos");
        } else {
            try {
                Conexion objCon = new Conexion();
                com.mysql.jdbc.Connection conn = objCon.getConexion();

                ps = conn.prepareStatement("UPDATE conductor SET Nombre=?, Telefono=?,Licencia=? WHERE Cedula=?");
                ps.setString(1, txtnombre2.getText());
                ps.setString(2, txttelefono3.getText());
                ps.setString(3, txtlicencia.getText());
                ps.setString(4, txtcedula2.getText());
                
                ps.execute();
                JOptionPane.showMessageDialog(null, "Conductor Modificado");

                limpiar();
                //tabla();

                //   conn.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error al Modificar conductor");
                System.err.println(ex);
            }
        }
        tabla();
    }//GEN-LAST:event_Modificar2ActionPerformed

    private void eliminar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar2ActionPerformed
        PreparedStatement ps = null;
        // txtId.setText("");
        //int Fila = tablausuarios.getSelectedRow();
        String comp = txtId.getText();
         int confirmacion = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea eliminar el registro del conductor?", "Confirmación", JOptionPane.YES_NO_OPTION);
        if (confirmacion == JOptionPane.YES_OPTION) {
            try {

            Conexion objCon = new Conexion();
            com.mysql.jdbc.Connection conn = objCon.getConexion();
            ps = conn.prepareStatement("DELETE FROM conductor WHERE Cedula=?");
            ps.setString(1, txtcedula2.getText());
            ps.execute();
            if ("".equals(comp)) {
                JOptionPane.showMessageDialog(null, "No se ha seleccionado ningun usuario");
            } else {
                JOptionPane.showMessageDialog(null, "Conductor Eliminado");
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al eliminar Conductor");
            System.out.println(ex.toString());
        }

        
        limpiar();
        tabla();
        }
        
    }//GEN-LAST:event_eliminar2ActionPerformed
 private boolean validaIngresos(java.awt.event.KeyEvent evt, int num) {

        char validar = evt.getKeyChar();
        if (num == 1) {
            if (Character.isDigit(validar)) {
                getToolkit().beep();
                evt.consume();
                return true;
            }
        } else {
            if (Character.isLetter(validar)) {
                getToolkit().beep();
                evt.consume();
                return true;
            }
        }

        return false;
    }
 public void tabla() {
        DefaultTableModel modelo = new DefaultTableModel();
        try {
            jtconductores.setModel(modelo);
            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion conn = new Conexion();
            java.sql.Connection con = conn.getConexion();

            String sql = "SELECT Cedula, Nombre, Telefono, Licencia FROM conductor";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();

            ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();

            modelo.addColumn("Cedula");
            modelo.addColumn("Nombre");
            modelo.addColumn("Telefono");
            modelo.addColumn("Licencia");
            
            int[] anchos = {70, 100, 70, 50};
            for (int i = 0; i < jtconductores.getColumnCount(); i++) {
                jtconductores.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
            }

            while (rs.next()) {
                Object[] filas = new Object[cantidadColumnas];
                for (int i = 0; i < cantidadColumnas; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                modelo.addRow(filas);
            }

        } catch (SQLException ex) {
            System.err.println(ex.toString());
        }
    }
  private void limpiar() {
        txtcedula2.setText("");
        txtnombre2.setText("");
        txttelefono3.setText("");
        txtlicencia.setText("");
        txtId.setText("");

    }
    private void txttelefono3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefono3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefono3ActionPerformed

    private void txttelefono3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefono3KeyTyped
         if (validaIngresos(evt, 2)) {
            JOptionPane.showMessageDialog(null, "Este campo no acepta letras");
        }
    }//GEN-LAST:event_txttelefono3KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTguardar2;
    private javax.swing.JPanel JPNregistrar2;
    private javax.swing.JButton Modificar2;
    private javax.swing.JButton btnBuscar2;
    private javax.swing.JButton eliminar2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTable jtconductores;
    private javax.swing.JLabel lblCedula2;
    private javax.swing.JLabel lblFechaNac7;
    private javax.swing.JLabel lblFechaNac8;
    private javax.swing.JTextField txtClave2;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtcedula2;
    private javax.swing.JTextField txtlicencia;
    private javax.swing.JTextField txtnombre2;
    private javax.swing.JTextField txttelefono3;
    // End of variables declaration//GEN-END:variables
}
