/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1_0;

import Atxy2k.CustomTextField.RestrictedTextField;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author matgr
 */
public class PanelClientes extends javax.swing.JPanel {

    /**
     * Creates new form PanelClientes
     */
    public PanelClientes() {
        initComponents();
        tabla();
        txtId.setVisible(false);
        RestrictedTextField r = new RestrictedTextField(txtcedula2);
        r.setLimit(10);
        RestrictedTextField r1 = new RestrictedTextField(txtClave2);
        r1.setLimit(10);
        RestrictedTextField r2 = new RestrictedTextField(txttelefono3);
        r2.setLimit(10);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        JPNregistrar2 = new javax.swing.JPanel();
        lblCedula2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtnombre2 = new javax.swing.JTextField();
        txtcedula2 = new javax.swing.JTextField();
        JBTguardar2 = new javax.swing.JButton();
        lblFechaNac7 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtClave2 = new javax.swing.JTextField();
        btnBuscar2 = new javax.swing.JButton();
        Modificar2 = new javax.swing.JButton();
        lblFechaNac8 = new javax.swing.JLabel();
        txttelefono3 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtdireccion = new javax.swing.JTextArea();
        txtId = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtclientes = new javax.swing.JTable();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("             CLIENTES");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        JPNregistrar2.setBackground(new java.awt.Color(255, 255, 255));

        lblCedula2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lblCedula2.setText("#Cédula:");

        jLabel6.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel6.setText("Nombre:");

        txtnombre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombre2ActionPerformed(evt);
            }
        });
        txtnombre2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombre2KeyTyped(evt);
            }
        });

        txtcedula2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcedula2ActionPerformed(evt);
            }
        });
        txtcedula2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcedula2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcedula2KeyTyped(evt);
            }
        });

        JBTguardar2.setText("Registrar");
        JBTguardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTguardar2ActionPerformed(evt);
            }
        });

        lblFechaNac7.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lblFechaNac7.setText("Dirección:");

        jLabel7.setText("Ingrese el numero de cédula del cliente:");

        txtClave2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClave2KeyTyped(evt);
            }
        });

        btnBuscar2.setText("Buscar");
        btnBuscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar2ActionPerformed(evt);
            }
        });

        Modificar2.setText("Modificar");
        Modificar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modificar2ActionPerformed(evt);
            }
        });

        lblFechaNac8.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lblFechaNac8.setText("Teléfono:");

        txttelefono3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelefono3ActionPerformed(evt);
            }
        });
        txttelefono3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelefono3KeyTyped(evt);
            }
        });

        txtdireccion.setColumns(20);
        txtdireccion.setRows(5);
        txtdireccion.setName("txtdireccion"); // NOI18N
        txtdireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdireccionKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(txtdireccion);

        txtId.setBackground(java.awt.SystemColor.control);
        txtId.setForeground(new java.awt.Color(255, 255, 255));
        txtId.setCaretColor(new java.awt.Color(255, 255, 255));
        txtId.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtId.setEnabled(false);

        javax.swing.GroupLayout JPNregistrar2Layout = new javax.swing.GroupLayout(JPNregistrar2);
        JPNregistrar2.setLayout(JPNregistrar2Layout);
        JPNregistrar2Layout.setHorizontalGroup(
            JPNregistrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNregistrar2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuscar2)
                .addGap(87, 87, 87))
            .addGroup(JPNregistrar2Layout.createSequentialGroup()
                .addGroup(JPNregistrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPNregistrar2Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(JPNregistrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFechaNac8)
                            .addComponent(lblCedula2)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFechaNac7))
                        .addGap(149, 149, 149))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPNregistrar2Layout.createSequentialGroup()
                        .addComponent(JBTguardar2)
                        .addGap(61, 61, 61)))
                .addGroup(JPNregistrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Modificar2)
                    .addComponent(txtcedula2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtClave2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttelefono3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JPNregistrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPNregistrar2Layout.createSequentialGroup()
                            .addComponent(txtnombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        JPNregistrar2Layout.setVerticalGroup(
            JPNregistrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNregistrar2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(JPNregistrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar2)
                    .addComponent(txtClave2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(JPNregistrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPNregistrar2Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(txtnombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPNregistrar2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JPNregistrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(JPNregistrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCedula2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcedula2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPNregistrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaNac8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttelefono3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPNregistrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPNregistrar2Layout.createSequentialGroup()
                        .addComponent(lblFechaNac7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(JPNregistrar2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(JPNregistrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JBTguardar2)
                            .addComponent(Modificar2))))
                .addContainerGap())
        );

        jPanel1.add(JPNregistrar2);
        JPNregistrar2.setBounds(0, 13, 692, 453);

        jTabbedPane1.addTab("Registro Clientes", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jtclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Cedula", "Nombre", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jtclientes);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tabla Clientes", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombre2ActionPerformed

    private void txtnombre2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombre2KeyTyped

        if (validaIngresos(evt, 1)) {
            JOptionPane.showMessageDialog(null, "Este campo no acepta numeros");
        }
    }//GEN-LAST:event_txtnombre2KeyTyped

    private void txtcedula2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcedula2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcedula2ActionPerformed

    private void txtcedula2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcedula2KeyReleased
        PreparedStatement ps = null;
        ResultSet rs = null;
        Conexion conn = new Conexion();

        try {

            java.sql.Connection con = conn.getConexion();
            ps = con.prepareStatement("SELECT * FROM cliente WHERE cedula = ?");
            ps.setString(1, txtcedula2.getText());

            rs = ps.executeQuery();

            if (rs.next()) {

                txtId.setText(txtcedula2.getText());

            } else {
                //JOptionPane.showMessageDialog(null, "Usuario no encontrado");
            }

        } catch (Exception e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_txtcedula2KeyReleased

    private void txtcedula2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcedula2KeyTyped

        if (validaIngresos(evt, 2)) {
            JOptionPane.showMessageDialog(null, "Este campo no acepta letras");
        }
    }//GEN-LAST:event_txtcedula2KeyTyped

    private void JBTguardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTguardar2ActionPerformed
        PreparedStatement ps = null;
        int num, contador = 2;

        int an;
        String comp = txtId.getText();

        //int Fila = tablausuarios.getSelectedRow();
        String comp1 = "";
        System.out.println(comp);
        if ("".equals(comp)) {
            comp = ".";
        }
        if ((comp1.equals(txtcedula2.getText())) || (comp1.equals(txtnombre2.getText())) || (comp1.equals(txttelefono3.getText())) || (comp1.equals(txtdireccion.getText()))) {
            JOptionPane.showMessageDialog(null, "Porfavor llene todos los campos");
        } else {
            if ((comp.equals(txtcedula2.getText()))) {
                JOptionPane.showMessageDialog(null, "El cliente ya se encuentra registrado");
            } else {
                num = Integer.parseInt(txtcedula2.getText());
                while (num / 10 > 0) {
                    num = num / 10;
                    contador++;
                }
                System.out.println(""+contador);
                if ((contador == 10)) {
                    try {
                        Conexion objCon = new Conexion();
                        Connection conn = objCon.getConexion();
                        ps = conn.prepareStatement("INSERT INTO cliente (Cedula, Nombre, Telefono, Direccion) VALUES (?,?,?,?)");
                        ps.setString(1, txtcedula2.getText());
                        ps.setString(2, txtnombre2.getText());

                        ps.setString(3, txttelefono3.getText());
                        ps.setString(4, txtdireccion.getText());

                        ps.execute();
                        JOptionPane.showMessageDialog(null, "Cliente Registrado");

                        limpiar();
                        // tabla();

                    } catch (SQLException ex) {

                        System.out.println(ex);
                        JOptionPane.showMessageDialog(null, "Error al registrar Cliente");
                    }
                }

                if (contador != 10) {
                    JOptionPane.showMessageDialog(null, "La cédula debe tener 10 dígitos");
                }
                tabla();

            }

        }
    }//GEN-LAST:event_JBTguardar2ActionPerformed

    private void txtClave2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClave2KeyTyped

        if (validaIngresos(evt, 2)) {
            JOptionPane.showMessageDialog(null, "Este campo no acepta letras");
        }
    }//GEN-LAST:event_txtClave2KeyTyped

    private void btnBuscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar2ActionPerformed
        // RestrictedTextField r = new RestrictedTextField(txtcedula2);
        //RestrictedTextField p=new RestrictedTextField(txtClave2);

        // p.setLimit(10);
        //p.setOnlyNums(true);
        PreparedStatement ps = null;
        ResultSet rs = null;
        Conexion conn = new Conexion();

        try {

            java.sql.Connection con = conn.getConexion();
            ps = con.prepareStatement("SELECT * FROM cliente WHERE Cedula = ?");
            ps.setString(1, txtClave2.getText());

            rs = ps.executeQuery();

            if (rs.next()) {
                txtcedula2.setText(rs.getString("Cedula"));
                txtnombre2.setText(rs.getString("Nombre"));
                txttelefono3.setText(rs.getString("Telefono"));

                txtdireccion.setText(rs.getString("Direccion"));
                txtId.setText(txtClave2.getText());

            } else {
                JOptionPane.showMessageDialog(null, "Cliente no encontrado");
            }

        } catch (Exception e) {
            System.err.println(e);
        }

        txtClave2.setText("");
    }//GEN-LAST:event_btnBuscar2ActionPerformed

    private void Modificar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Modificar2ActionPerformed
        // Conexion conn = new Conexion();
        PreparedStatement ps = null;
        //int Fila = tablausuarios.getSelectedRow();
        if (("".equals(txtcedula2.getText())) || ("".equals(txtnombre2.getText())) || ("".equals(txttelefono3.getText())) || ("".equals(txtdireccion.getText()))) {
            JOptionPane.showMessageDialog(null, "Todos los campos deben estar llenos");
        } else {
            try {
                Conexion objCon = new Conexion();
                com.mysql.jdbc.Connection conn = objCon.getConexion();

                ps = conn.prepareStatement("UPDATE cliente SET Nombre=?, Telefono=?,Direccion=? WHERE Cedula=?");
                ps.setString(1, txtnombre2.getText());
                ps.setString(2, txttelefono3.getText());
                ps.setString(3, txtdireccion.getText());
                ps.setString(4, txtcedula2.getText());

                ps.execute();
                JOptionPane.showMessageDialog(null, "Cliente Modificado");

                limpiar();
                //tabla();

                //   conn.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error al Modificar cliente");
                System.err.println(ex);
            }
        }
        tabla();
    }//GEN-LAST:event_Modificar2ActionPerformed
    private boolean validaIngresos(java.awt.event.KeyEvent evt, int num) {

        char validar = evt.getKeyChar();
        if (num == 1) {
            if (Character.isDigit(validar)) {
                getToolkit().beep();
                evt.consume();
                return true;
            }
        } else {
            if (Character.isLetter(validar)) {
                getToolkit().beep();
                evt.consume();
                return true;
            }
        }

        return false;
    }

    public void tabla() {
        DefaultTableModel modelo = new DefaultTableModel();
        try {
            jtclientes.setModel(modelo);
            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion conn = new Conexion();
            java.sql.Connection con = conn.getConexion();

            String sql = "SELECT Cedula, Nombre, Telefono, Direccion FROM cliente";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();

            ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();

            modelo.addColumn("Cedula");
            modelo.addColumn("Nombre");
            modelo.addColumn("Telefono");
            modelo.addColumn("Direccion");

            int[] anchos = {70, 100, 70, 50};
            for (int i = 0; i < jtclientes.getColumnCount(); i++) {
                jtclientes.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
            }

            while (rs.next()) {
                Object[] filas = new Object[cantidadColumnas];
                for (int i = 0; i < cantidadColumnas; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                modelo.addRow(filas);
            }

        } catch (SQLException ex) {
            System.err.println(ex.toString());
        }
    }

    private void limpiar() {
        txtcedula2.setText("");
        txtnombre2.setText("");
        txttelefono3.setText("");
        txtdireccion.setText("");
        txtId.setText("");

    }
    private void txttelefono3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefono3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefono3ActionPerformed

    private void txttelefono3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefono3KeyTyped
        if (validaIngresos(evt, 2)) {
            JOptionPane.showMessageDialog(null, "Este campo no acepta letras");
        }
    }//GEN-LAST:event_txttelefono3KeyTyped

    private void txtdireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdireccionKeyTyped
        if (validaIngresos(evt, 1)) {
            JOptionPane.showMessageDialog(null, "Este campo no acepta numeros");
        }
    }//GEN-LAST:event_txtdireccionKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTguardar2;
    private javax.swing.JPanel JPNregistrar2;
    private javax.swing.JButton Modificar2;
    private javax.swing.JButton btnBuscar2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable jtclientes;
    private javax.swing.JLabel lblCedula2;
    private javax.swing.JLabel lblFechaNac7;
    private javax.swing.JLabel lblFechaNac8;
    private javax.swing.JTextField txtClave2;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtcedula2;
    private javax.swing.JTextArea txtdireccion;
    private javax.swing.JTextField txtnombre2;
    private javax.swing.JTextField txttelefono3;
    // End of variables declaration//GEN-END:variables
}
