/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1_0;

import Atxy2k.CustomTextField.RestrictedTextField;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author matgr
 */
public class PanelBuses extends javax.swing.JPanel {

    /**
     * Creates new form PanelBuses
     */
    public PanelBuses() {
        initComponents();
        txtId.setVisible(false);
        RestrictedTextField r = new RestrictedTextField(txtdisco);
        r.setLimit(4);
        RestrictedTextField r1 = new RestrictedTextField(txtClave2);
        r1.setLimit(4);
        RestrictedTextField r2 = new RestrictedTextField(txtplaca);
        r2.setLimit(4);
        RestrictedTextField r3 = new RestrictedTextField(txtplaca1);
        r3.setLimit(3);
        RestrictedTextField r4 = new RestrictedTextField(txtcapacidad);
        r4.setLimit(2);
        try {

            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion conn = new Conexion();
            java.sql.Connection con = conn.getConexion();

            String sql = "SELECT  Nombre FROM conductor";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();

            ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();

            while (rs.next()) {

                for (int i = 0; i < cantidadColumnas; i++) {
                    cboConductor.addItem("" + rs.getObject(i + 1));
                }

            }

        } catch (SQLException ex) {
            System.err.println(ex.toString());
        }
        tabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        JPNregistrar2 = new javax.swing.JPanel();
        lblCedula2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtplaca = new javax.swing.JTextField();
        JBTguardar2 = new javax.swing.JButton();
        lblFechaNac7 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtClave2 = new javax.swing.JTextField();
        btnBuscar2 = new javax.swing.JButton();
        Modificar2 = new javax.swing.JButton();
        lblFechaNac8 = new javax.swing.JLabel();
        txtcapacidad = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtdisco = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtmarca = new javax.swing.JTextField();
        lblguion = new javax.swing.JLabel();
        txtplaca1 = new javax.swing.JTextField();
        cboConductor = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtclientes = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("             BUSES");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        JPNregistrar2.setBackground(new java.awt.Color(255, 255, 255));
        JPNregistrar2.setLayout(null);

        lblCedula2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lblCedula2.setText("#Conductor designado:");
        JPNregistrar2.add(lblCedula2);
        lblCedula2.setBounds(100, 230, 170, 25);

        jLabel6.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel6.setText("Nº Disco:");
        JPNregistrar2.add(jLabel6);
        jLabel6.setBounds(100, 130, 80, 25);

        txtplaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtplacaActionPerformed(evt);
            }
        });
        txtplaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtplacaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtplacaKeyTyped(evt);
            }
        });
        JPNregistrar2.add(txtplaca);
        txtplaca.setBounds(400, 180, 50, 22);

        JBTguardar2.setText("Registrar");
        JBTguardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTguardar2ActionPerformed(evt);
            }
        });
        JPNregistrar2.add(JBTguardar2);
        JBTguardar2.setBounds(186, 415, 85, 25);

        lblFechaNac7.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lblFechaNac7.setText("Capacidad:");
        JPNregistrar2.add(lblFechaNac7);
        lblFechaNac7.setBounds(100, 350, 80, 25);

        jLabel7.setText("Ingrese el Nº de disco del bus:");
        JPNregistrar2.add(jLabel7);
        jLabel7.setBounds(12, 56, 190, 25);

        txtClave2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClave2KeyTyped(evt);
            }
        });
        JPNregistrar2.add(txtClave2);
        txtClave2.setBounds(332, 57, 109, 22);

        btnBuscar2.setText("Buscar");
        btnBuscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar2ActionPerformed(evt);
            }
        });
        JPNregistrar2.add(btnBuscar2);
        btnBuscar2.setBounds(534, 56, 71, 25);

        Modificar2.setText("Modificar");
        Modificar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modificar2ActionPerformed(evt);
            }
        });
        JPNregistrar2.add(Modificar2);
        Modificar2.setBounds(332, 415, 85, 25);

        lblFechaNac8.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lblFechaNac8.setText("Marca del Bus:");
        JPNregistrar2.add(lblFechaNac8);
        lblFechaNac8.setBounds(100, 290, 130, 25);

        txtcapacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcapacidadActionPerformed(evt);
            }
        });
        txtcapacidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcapacidadKeyTyped(evt);
            }
        });
        JPNregistrar2.add(txtcapacidad);
        txtcapacidad.setBounds(330, 350, 30, 22);

        txtId.setBackground(java.awt.SystemColor.control);
        txtId.setForeground(new java.awt.Color(255, 255, 255));
        txtId.setCaretColor(new java.awt.Color(255, 255, 255));
        txtId.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtId.setEnabled(false);
        JPNregistrar2.add(txtId);
        txtId.setBounds(512, 163, 146, 22);

        txtdisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdiscoActionPerformed(evt);
            }
        });
        txtdisco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdiscoKeyTyped(evt);
            }
        });
        JPNregistrar2.add(txtdisco);
        txtdisco.setBounds(330, 130, 50, 22);

        jLabel9.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel9.setText("Nº Placa:");
        JPNregistrar2.add(jLabel9);
        jLabel9.setBounds(100, 180, 80, 25);

        txtmarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmarcaActionPerformed(evt);
            }
        });
        txtmarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmarcaKeyTyped(evt);
            }
        });
        JPNregistrar2.add(txtmarca);
        txtmarca.setBounds(330, 290, 160, 22);

        lblguion.setText("   -");
        JPNregistrar2.add(lblguion);
        lblguion.setBounds(370, 180, 20, 16);

        txtplaca1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtplaca1ActionPerformed(evt);
            }
        });
        txtplaca1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtplaca1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtplaca1KeyTyped(evt);
            }
        });
        JPNregistrar2.add(txtplaca1);
        txtplaca1.setBounds(330, 180, 40, 22);

        cboConductor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione" }));
        JPNregistrar2.add(cboConductor);
        cboConductor.setBounds(330, 230, 110, 22);

        jPanel2.add(JPNregistrar2);
        JPNregistrar2.setBounds(0, 13, 720, 500);

        jTabbedPane1.addTab("Registro Buses", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jtclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Cedula", "Nombre", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jtclientes);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tabla Buses", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(239, 239, 239))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 749, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtplacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtplacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtplacaActionPerformed

    private void txtplacaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtplacaKeyReleased

    }//GEN-LAST:event_txtplacaKeyReleased

    private void txtplacaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtplacaKeyTyped

        if (validaIngresos(evt, 2)) {
            JOptionPane.showMessageDialog(null, "Este campo no acepta letras");
        }
    }//GEN-LAST:event_txtplacaKeyTyped

    private void JBTguardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTguardar2ActionPerformed
        PreparedStatement ps = null;
        int num, contador = 1;

        int an = buscar1();
        String comp = txtId.getText();

        //int Fila = tablausuarios.getSelectedRow();
        String comp1 = "";
        System.out.println(comp);
        if ("".equals(comp)) {
            comp = ".";
        }
        if ((comp1.equals(txtplaca.getText())) || (comp1.equals(txtplaca1.getText())) || (comp1.equals(txtcapacidad.getText())) || (comp1.equals(txtdisco.getText())) || (comp1.equals(txtmarca.getText())) || (cboConductor.getSelectedIndex() == 0)) {
            JOptionPane.showMessageDialog(null, "Porfavor llene todos los campos");
        } else {
            if (an == 1) {
                JOptionPane.showMessageDialog(null, "El bus ya se encuentra registrado");
            } else {
                int conv = Integer.parseInt(txtcapacidad.getText());
                if ((conv >= 30) && (conv <= 40)) {
                    try {
                        Conexion objCon = new Conexion();
                        Connection conn = objCon.getConexion();
                        ps = conn.prepareStatement("INSERT INTO bus (Disco, Placa, Conductor, Marca, Capacidad) VALUES (?,?,?,?,?)");
                        ps.setString(1, txtdisco.getText());
                        ps.setString(2, txtplaca1.getText() + "-" + txtplaca.getText());
                        ps.setString(3, cboConductor.getSelectedItem().toString());
                        ps.setString(4, txtmarca.getText());
                        ps.setString(5, txtcapacidad.getText());

                        ps.execute();
                        JOptionPane.showMessageDialog(null, "Bus Registrado");

                        limpiar();
                        // tabla();

                    } catch (SQLException ex) {

                        System.out.println(ex);
                        JOptionPane.showMessageDialog(null, "Error al registrar Bus");
                    }

                    tabla();

                } else {
                    JOptionPane.showMessageDialog(null, "La capacidad del bus se encuentra fuera de rango");
                }

            }

        }
    }//GEN-LAST:event_JBTguardar2ActionPerformed

    private void txtClave2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClave2KeyTyped

        if (validaIngresos(evt, 2)) {
            JOptionPane.showMessageDialog(null, "Este campo no acepta letras");
        }
    }//GEN-LAST:event_txtClave2KeyTyped

    private void btnBuscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar2ActionPerformed
        // RestrictedTextField r = new RestrictedTextField(txtplaca);
        //RestrictedTextField p=new RestrictedTextField(txtClave2);

        // p.setLimit(10);
        //p.setOnlyNums(true);
        PreparedStatement ps = null;
        ResultSet rs = null;
        Conexion conn = new Conexion();
        String[] sep;
        String sep1;
        try {

            java.sql.Connection con = conn.getConexion();
            ps = con.prepareStatement("SELECT * FROM bus WHERE Disco = ?");
            ps.setString(1, txtClave2.getText());

            rs = ps.executeQuery();

            if (rs.next()) {
                txtdisco.setText(rs.getString("Disco"));
                sep1 = rs.getString("Placa");
                sep = sep1.split("-");
                txtplaca1.setText(sep[0]);
                txtplaca.setText(sep[1]);
                cboConductor.setSelectedItem(rs.getString("Conductor"));

                txtmarca.setText(rs.getString("Marca"));
                txtcapacidad.setText(rs.getString("Capacidad"));

            } else {
                JOptionPane.showMessageDialog(null, "Bus no encontrado");
            }

        } catch (Exception e) {
            System.err.println(e);
        }

        txtClave2.setText("");
    }//GEN-LAST:event_btnBuscar2ActionPerformed

    private void Modificar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Modificar2ActionPerformed
        // Conexion conn = new Conexion();
        PreparedStatement ps = null;
        String comp1 = "";
        //int Fila = tablausuarios.getSelectedRow();
        if ((comp1.equals(txtplaca.getText())) || (comp1.equals(txtplaca1.getText())) || (comp1.equals(txtcapacidad.getText())) || (comp1.equals(txtdisco.getText())) || (comp1.equals(txtmarca.getText())) || (cboConductor.getSelectedIndex() == 0)) {
            JOptionPane.showMessageDialog(null, "Todos los campos deben estar llenos");
        } else {
            try {
                Conexion objCon = new Conexion();
                com.mysql.jdbc.Connection conn = objCon.getConexion();

                ps = conn.prepareStatement("UPDATE bus SET Conductor=?,Marca=?,Capacidad=? WHERE Disco=? AND Placa=?");

                ps.setString(1, cboConductor.getSelectedItem().toString());
                ps.setString(2, txtmarca.getText());
                ps.setString(3, txtcapacidad.getText());
                ps.setString(4, txtdisco.getText());
                ps.setString(5, txtplaca1.getText() + "-" + txtplaca.getText());
                ps.execute();
                JOptionPane.showMessageDialog(null, "Bus Modificado");

                limpiar();
                //tabla();

                //   conn.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error al Modificar bus");
                System.err.println(ex);
            }
        }
        tabla();
    }//GEN-LAST:event_Modificar2ActionPerformed

    private void txtcapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcapacidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcapacidadActionPerformed

    private void txtcapacidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcapacidadKeyTyped
        if (validaIngresos(evt, 2)) {
            JOptionPane.showMessageDialog(null, "Este campo no acepta letras");
        }
    }//GEN-LAST:event_txtcapacidadKeyTyped

    private void txtdiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdiscoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdiscoActionPerformed

    private void txtdiscoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdiscoKeyTyped
        if (validaIngresos(evt, 2)) {
            JOptionPane.showMessageDialog(null, "Este campo no acepta letras");
        }
    }//GEN-LAST:event_txtdiscoKeyTyped

    private void txtmarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmarcaActionPerformed

    private void txtmarcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmarcaKeyTyped
        if (validaIngresos(evt, 1)) {
            JOptionPane.showMessageDialog(null, "Este campo no acepta numeros");
        }
    }//GEN-LAST:event_txtmarcaKeyTyped

    private void txtplaca1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtplaca1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtplaca1ActionPerformed

    private void txtplaca1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtplaca1KeyReleased

    }//GEN-LAST:event_txtplaca1KeyReleased

    private void txtplaca1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtplaca1KeyTyped
        if (validaIngresos(evt, 1)) {
            JOptionPane.showMessageDialog(null, "Este campo no acepta numeros");
        }
    }//GEN-LAST:event_txtplaca1KeyTyped
    private boolean validaIngresos(java.awt.event.KeyEvent evt, int num) {

        char validar = evt.getKeyChar();
        if (num == 1) {
            if (Character.isDigit(validar)) {
                getToolkit().beep();
                evt.consume();
                return true;
            }
        } else {
            if (Character.isLetter(validar)) {
                getToolkit().beep();
                evt.consume();
                return true;
            }
        }

        return false;
    }

    private int buscar1() {
        int dev = 0;
        PreparedStatement ps = null;
        ResultSet rs = null;
        Conexion conn = new Conexion();

        try {

            java.sql.Connection con = conn.getConexion();
            ps = con.prepareStatement("SELECT * FROM bus WHERE Disco = ? OR Placa = ?");
            ps.setString(1, txtdisco.getText());
            ps.setString(2, txtplaca1.getText() + "-" + txtplaca.getText());

            rs = ps.executeQuery();

            if (rs.next()) {

                dev = 1;

            } else {
                //JOptionPane.showMessageDialog(null, "Usuario no encontrado");
            }

        } catch (Exception e) {
            System.err.println(e);
        }
        return dev;
    }

    public void tabla() {
        DefaultTableModel modelo = new DefaultTableModel();
        try {
            jtclientes.setModel(modelo);
            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion conn = new Conexion();
            java.sql.Connection con = conn.getConexion();

            String sql = "SELECT Disco, Placa, Conductor, Marca, Capacidad FROM bus";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();

            ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();

            modelo.addColumn("Nº Disco");
            modelo.addColumn("Nº Placa");
            modelo.addColumn("Conductor");
            modelo.addColumn("Marca del Bus");
            modelo.addColumn("Capacidad");

            int[] anchos = {50, 50, 70, 50, 30};
            for (int i = 0; i < jtclientes.getColumnCount(); i++) {
                jtclientes.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
            }

            while (rs.next()) {
                Object[] filas = new Object[cantidadColumnas];
                for (int i = 0; i < cantidadColumnas; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                modelo.addRow(filas);
            }

        } catch (SQLException ex) {
            System.err.println(ex.toString());
        }
    }

    private void limpiar() {
        txtdisco.setText("");
        txtplaca.setText("");
        txtplaca1.setText("");
        txtmarca.setText("");
        txtcapacidad.setText("");
        cboConductor.setSelectedIndex(0);
        txtId.setText("");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTguardar2;
    private javax.swing.JPanel JPNregistrar2;
    private javax.swing.JButton Modificar2;
    private javax.swing.JButton btnBuscar2;
    private javax.swing.JComboBox<String> cboConductor;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jtclientes;
    private javax.swing.JLabel lblCedula2;
    private javax.swing.JLabel lblFechaNac7;
    private javax.swing.JLabel lblFechaNac8;
    private javax.swing.JLabel lblguion;
    private javax.swing.JTextField txtClave2;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtcapacidad;
    private javax.swing.JTextField txtdisco;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtplaca;
    private javax.swing.JTextField txtplaca1;
    // End of variables declaration//GEN-END:variables
}
